export const UPDATE_PLACES_RESULTS = 'UPDATE_PLACES_RESULTS'
export const SET_IS_LOADING = 'SET_IS_LOADING'
export const PLACE_SELECTED = 'PLACE_SELECTED'
export const UPDATE_PLACE_DETAILS = 'UPDATE_PLACE_DETAILS'